version: '3'
services:
  kong:
    image: kong:latest
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    environment:
      KONG_PG_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
